export const GET_USER = 'GET_USER';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';
export const GET_RESET_USER = 'GET_RESET_USER';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';
export const GET_RESET_POST = 'GET_RESET_POST';

export const GET_ALBUM = 'GET_ALBUM';
export const GET_ALBUM_PENDING = 'GET_ALBUM_PENDING';
export const GET_ALBUM_FULFILLED = 'GET_ALBUM_FULFILLED';
export const GET_ALBUM_REJECTED = 'GET_ALBUM_REJECTED';
export const GET_RESET_ALBUM = 'GET_RESET_ALBUM';

export const GET_PHOTO = 'GET_PHOTO';
export const GET_PHOTO_PENDING = 'GET_PHOTO_PENDING';
export const GET_PHOTO_FULFILLED = 'GET_PHOTO_FULFILLED';
export const GET_PHOTO_REJECTED = 'GET_PHOTO_REJECTED';
export const GET_RESET_PHOTO = 'GET_RESET_PHOTO';

export const POST_PHOTO = 'POST_PHOTO';
export const POST_PHOTO_PENDING = 'POST_PHOTO_PENDING';
export const POST_PHOTO_FULFILLED = 'POST_PHOTO_FULFILLED';
export const POST_PHOTO_REJECTED = 'POST_PHOTO_REJECTED';


export const PUT_PHOTO = 'PUT_PHOTO';
export const PUT_PHOTO_PENDING = 'PUT_PHOTO_PENDING';
export const PUT_PHOTO_FULFILLED = 'PUT_PHOTO_FULFILLED';
export const PUT_PHOTO_REJECTED = 'PUT_PHOTO_REJECTED';

export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTO_PENDING = 'DELETE_PHOTO_PENDING';
export const DELETE_PHOTO_FULFILLED = 'DELETE_PHOTO_FULFILLED';
export const DELETE_PHOTO_REJECTED = 'DELETE_PHOTO_REJECTED';

export const POST_POSTING = 'POST_POSTING';
export const POST_POSTING_PENDING = 'POST_POSTING_PENDING';
export const POST_POSTING_FULFILLED = 'POST_POSTING_FULFILLED';
export const POST_POSTING_REJECTED = 'POST_POSTING_REJECTED';


export const PUT_POST = 'PUT_POST';
export const PUT_POST_PENDING = 'PUT_POST_PENDING';
export const PUT_POST_FULFILLED = 'PUT_POST_FULFILLED';
export const PUT_POST_REJECTED = 'PUT_POST_REJECTED';


export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED';
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED';