export const GET_USER = 'GET_USER';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';
export const GET_RESET_USER = 'GET_RESET_USER';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';
export const GET_RESET_POST = 'GET_RESET_POST';

export const GET_ALBUM = 'GET_ALBUM';
export const GET_ALBUM_PENDING = 'GET_ALBUM_PENDING';
export const GET_ALBUM_FULFILLED = 'GET_ALBUM_FULFILLED';
export const GET_ALBUM_REJECTED = 'GET_ALBUM_REJECTED';
export const GET_RESET_ALBUM = 'GET_RESET_ALBUM';

export const GET_PHOTO = 'GET_PHOTO';
export const GET_PHOTO_PENDING = 'GET_PHOTO_PENDING';
export const GET_PHOTO_FULFILLED = 'GET_PHOTO_FULFILLED';
export const GET_PHOTO_REJECTED = 'GET_PHOTO_REJECTED';
export const GET_RESET_PHOTO = 'GET_RESET_PHOTO';
